services:
  placeholder:
    image: alpine:3.23.5
    container_name: core_service
    command: [ "sh", "-c", "echo 'This is a placeholder sevice' && sleep infinity" ]
    networks:
      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    external: false
    # ВАЖНО: здесь мы создаём сеть с именем microservices-net
    # Другие docker-compose файлы будут к ней подключаться с external: true
