// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	order "github.com/LushnikovSR/spaceship_factory/order/internal/model"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: _a0
func (_m *OrderRepository) CreateOrder(_a0 *order.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*order.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - _a0 *order.Order
func (_e *OrderRepository_Expecter) CreateOrder(_a0 interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", _a0)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(_a0 *order.Order)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*order.Order))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(*order.Order) error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: uuid
func (_m *OrderRepository) GetOrder(uuid string) *order.Order {
	ret := _m.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *order.Order
	if rf, ok := ret.Get(0).(func(string) *order.Order); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	return r0
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrder(uuid interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", uuid)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(uuid string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(_a0 *order.Order) *OrderRepository_GetOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(string) *order.Order) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: _a0
func (_m *OrderRepository) UpdateOrder(_a0 *order.Order) {
	_m.Called(_a0)
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - _a0 *order.Order
func (_e *OrderRepository_Expecter) UpdateOrder(_a0 interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", _a0)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(_a0 *order.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*order.Order))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return() *OrderRepository_UpdateOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(*order.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Run(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
