// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// Checks the order status. If `PENDING_PAYMENT`, changes the status to `CANCELLED`. If `PAID`,
	// returns a 409 error.
	//
	// POST /orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Получает детали через `InventoryService.ListParts`. Проверяет, что
	// все детали существуют. Если хотя бы одной нет —
	// возвращает ошибку. Считает `total_price`. Генерирует `order_uuid`.
	//  Сохраняет заказ со статусом `PENDING_PAYMENT`.
	//
	// POST /orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrder implements getOrder operation.
	//
	// Get order by uuid.
	//
	// GET /orders/{order_uuid}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// PayOrder implements payOrder operation.
	//
	// Находит заказ по `order_uuid`. Если не существует —
	// возвращает 404 Not Found. Вызывает `PaymentService.PayOrder`, передаёт
	// `user_uuid`, `order_uuid` и `payment_method`. Получает`transaction_uuid`.
	// Обновляет заказ: статус → `PAID`, сохраняет `transaction_uuid`,
	// `payment_method`.
	//
	// POST /orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
